### PR TITLE
Go samples

### PR DESCRIPTION
**Pull request by yangb8**
there  are 2 commits: 

1. "Add vendor code for go samples" is just vendor code, big but could be ignored for review.
2. "Add ECS samples with golang on top of AWS GO SDK" is the sample code by go.

### CODE REVIEW

**Comment by jasoncwik** [comment]
Wouldn't there be some way to have Makefile execute 'go get' instead of checking in all the vendor code?

**Comment by DavidASeibert** [comment]
Yes, that’s definitely possible. Haven’t done it in gradle, but maven code can do that, so I’d assume gradle can as well.

David Seibert
Principal Software Engineer, ECS Customer Advisory Team
DELL EMC | Advanced Software Division
mobile +1 919-656-0619
david.seibert@dell.com

**Review by DavidASeibert — CHANGES_REQUESTED** [review]
Why are we including all of the vendor files? The build file should download them instead, if necessary by adding a second project to do this.

**Comment by yangb8** [comment]
Technically, yes, we can leverage build tool to download dependency code during build, but it's just not golang way :). 

to bring all dependency to repository is the recommended approach for golang's package management; it's also one of different parts between golang and other languages, and actually, it's a good question/concern, and lots of arguments. 

golang import is decentralized management, so programers can pull code from anywhere but not just a central official repository. Consequently, we don't want to break the build just because the imported code is changed by that code's owner, or various developers build out different binaries due to pulling different dependency code. So the solution is to bring dependency code to local repository, it's not best solution, but works for golang. 

FYI. https://golang.org/doc/faq#get_version

**Comment by DavidASeibert** [comment]
This could be a composite project, though – one sub-project to import the dependent code to the local repository, and another to do the golfing build from the imported code. That would be a much cleaner split. If you’re worried about a change, you could have the project refer to a specific version, tag, or commit of the dependent code. 

The FAQ says that simply that the Go developers don't want to force their versioning implementation on all users, it doesn't say that users shouldn't use their own versioning scheme.

**Comment by yangb8** [comment]
Hey David, thanks for your comments! Like I mentioned, this is golang's way to handle dependency though there are many difference voices. and actually, google adopts the same way for dependency code. On the other hand, I also agree with you that ecs-sample is kind of special because it is a composite repository. So I can make the change to fetch vendor code during build, rather than following golong's normal approach to put everything in local repository.

Let me know if you have any other comments.

**Comment by yangb8** [comment]
Make code change per comments.

**Comment by yangb8** [comment]
can I get +1 or further comments?

**Comment by yangb8** [comment]
make some enhancement for Makefile and README.

Current status:
 1. can build the project by go(make) and docker in command line on both Mac and Linux
 2. can build the project by go(make) in Eclipse
 3. add steps in README about how to fully enable godef (jump to symbol definition), as well as limitation.

Just feel like both Eclipse and IJ don't support golang well, maybe just because the plugin for golang is still premature to handle various customization.

Let me know if you have any other comments

**Comment by yangb8** [comment]
Is there any further comment?

**Comment by yangb8** [comment]
I prefer to merge this PR if no more comments by end of this friday. will submit new PR to track any further comments and/or requests.

**Comment by DavidASeibert** [comment]
Sounds good. I will look at it today or tomorrow. Sorry about the delay.

**Pull request merged**
